# Prompts, mode, accent settings
introduction_prompt: "Hi {candidate_name}, welcome to the interview..."
conclusion_prompt: "Thank you for your time. We'll follow up soon."
mode: "AGENT"  # or "TRANSCRIBER"
accent: "en-US-Standard-C"  # or "en-IN-Standard-A"
language_code: "en-US"